name: JMeter Performance Test

on:
  workflow_dispatch:
    inputs:
      threads:
        description: 'Number of concurrent users (threads)'
        required: true
        default: '50'
      rampup_time:
        description: 'Ramp-up period in seconds'
        required: true
        default: '5'
      duration:
        description: 'Test duration in seconds'
        required: false
        default: '60'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-jmeter-tests:
    env:
      JMETER_VERSION: 5.6.3
    environment: jmeter-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache JMeter
        id: jmeter-cache
        uses: actions/cache@v4
        with:
          path: apache-jmeter-${{ env.JMETER_VERSION }}
          key: ${{ runner.os }}-jmeter-${{ env.JMETER_VERSION }}

      - name: Setup JMeter
        if: steps.jmeter-cache.outputs.cache-hit != 'true'
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.JMETER_VERSION }}.tgz
          tar -xzf apache-jmeter-${{ env.JMETER_VERSION }}.tgz

      - name: Set JMETER_HOME
        run: echo "JMETER_HOME=$PWD/apache-jmeter-${{ env.JMETER_VERSION }}" >> $GITHUB_ENV

      - name: Run JMeter Test
        run: |
          rm -rf target/
          mkdir -p target/reports

          $JMETER_HOME/bin/jmeter \
            -n \
            -t "src/test/jmeter/Automation Exercise - Performance Tests - JMeter.jmx" \
            -Jthreads=${{ github.event.inputs.threads }} \
            -Jrampup=${{ github.event.inputs.rampup_time }} \
            -Jduration=${{ github.event.inputs.duration }} \
            -l "target/results/test-results.jtl" \
            -e \
            -o "target/reports"

      - name: Upload JMeter report
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/reports'

  deploy-report:
    needs: run-jmeter-tests
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4